---
title: "Practical exercises"
author: "Tobias Rüttenauer"
date: "July 02, 2022"
output_dir: docs
output: 
  html_document:
    theme: flatly
    highlight: haddock
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
theme: united
bibliography: sicss-spatial.bib
link-citations: yes
---

# Practical exercises

See below three practical exercises. Please choose the one you are most interested in. In case you are quick, try the remaining exercises. 

1. Add a variable for the distance to Boris Johnson's home (10 Downing St, London SW1A 2AB, UK). 

    * You could either find the coordinates manually or you use `tmaptools` function `geocode_OSM()` to query OpenStreetMaps API for geo-coding. 
    
    * There are also Google Maps APIs like `ggmap` or `mapsapi` but they require registration.
    

2. Please think about other potential variables you could add to the previous data which might be relevant for predicting NO2.

  * You can for instance use the census API, or the OpenStreetMap API.
  
  * You can also search for other data in the [London Datastore](https://data.london.gov.uk/dataset/cultural-infrastructure-map). 
  
  * You can also search for something completely different.
    

3. Given you have added new data, can you use some model to predict the importance of single variables for predicting NO2 levels across London?

4. In case you still have some time left, can you draw a map of the spatial distribution of deprivation in England?

  * The [Index of Multiple Deprivation](https://www.gov.uk/guidance/english-indices-of-deprivation-2019-mapping-resources) offers several resources for mapping.
  
  * [Geoportal](https://geoportal.statistics.gov.uk/) is a great resource for geographical boundaries.  